### ISSUE TITLE
How to filter for example orders?

### ISSUE THREAD

**Issue by rschueler** [apertureless/shopware-api-client#15]
Hi, as far as I understood there is no way of requesting only orders of a given status. It would be great if you could add filtering.

**Comment by apertureless** [comment]
Will add it.

**Comment by apertureless** [comment]
Should be implemented now in `v1.1.0` 

You can now pass parameters to the `getOrders(params)` method.

Checkout the [Shopware docs](https://developers.shopware.com/developers-guide/rest-api/examples/order/) how the filters should look like. So you can build your own filtering and pass the parameters to getOrders().

However I could not test it well, because my testshop frontend is broken right now, so I can only interact over the api. So I could not create some sample orders to test it.
